### ISSUE TITLE
Latest "Gathering Skill" Version causes Fatal load error

### ISSUE THREAD

**Issue by XzeroAir** [pipakin/PipakinsMods#3] opened 2021-03-12 05:37 UTC
when using the Latest Gathering Skill version, 1.2.0, With Crop Replant Version, 2.1.1, I had a Fatal load error stating "Cyclic dependency Error", which caused no mods to load at all.

Reverting back to an older version Fixed the issue for me.

if you require more information, let me know

**Comment by pipakin** [comment] 2021-03-12 06:11
I'll check first thing tomorrow. It's possible we both tried to add
compatibility patches and broke each other.

**Comment by pipakin** [comment] 2021-03-12 17:05
This is now fixed with version 1.2.1. Looks like the root cause was CropReplant also adding a dependency on my mod in their version 2.1.1. I've modified the way I do the compatibility patch so that my main mod doesn't depend on theirs (there is a small sub mod that does it). I tested it locally and it solves the issue.

**Closed as completed by pipakin** 2021-03-12 17:05 UTC

**Comment by XzeroAir** [comment] 2021-03-13 12:19
Yep, Looks fixed, Thanks
